// <auto-generated />
namespace Semana10.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class V105 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(V105));
        
        string IMigrationMetadata.Id
        {
            get { return "202006090006380_V1.0.5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
