// <auto-generated />
namespace Semana10.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class V104 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(V104));
        
        string IMigrationMetadata.Id
        {
            get { return "202006082340254_V1.0.4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
